/* js/tools-part-2.js - Tools Part 2 (CSS, DevOps, Content, Math, Media) */
window.toolsPart2 = [
  // 6. CSS, STYLING & UI DESIGN
  ['box-shadow', 'CSS Box-Shadow Studio', 'Visual sliders for offsets, blur, and spread with instant CSS copy', 'design', 'layers', 'CSS Studio'],
  ['flexbox-play', 'CSS Flexbox Playground', 'Interactive visual sandbox for justify-content, align-items, and flex-wrap', 'design', 'layout', 'Flexbox'],
  ['grid-gen', 'CSS Grid Code Generator', 'Design responsive CSS grid layouts visually with template columns and rows', 'design', 'grid-3x3', 'Grid'],
  ['color-convert', 'HEX to RGB / HSL Converter', 'Interactive color spectrum picker with instant HEX, RGBA, and HSL copy formats', 'design', 'pipette', 'Color'],
  ['palette-gen', 'Color Palette Harmony Builder', 'Generate complementary, analogous, and triadic color schemes with hex copy', 'design', 'palette', 'Harmony'],
  ['glassmorphism', 'CSS Glassmorphism Generator', 'Configure frosted glass blur, opacity, and saturation CSS styles', 'design', 'sparkle', 'Glass'],
  ['border-radius', 'CSS Border-Radius Studio', 'Visually configure 8-point asymmetric border-radius organic shapes', 'design', 'square', 'Shapes'],
  ['gradient-gen', 'CSS Linear & Radial Gradient Generator', 'Build multi-stop color transitions and export clean CSS background styles', 'design', 'sun-medium', 'Gradients'],
  ['css-minifier', 'CSS Minifier & Optimizer', 'Strip redundant whitespace, comments, and optimize CSS styles for speed', 'design', 'file-minus', 'Speed'],
  ['aspect-ratio', 'Aspect Ratio Calculator', 'Compute responsive dimensions for 16:9, 4:3, 1:1, and custom resolutions', 'design', 'maximize', 'Ratio'],
  ['px-to-rem', 'PX to REM & REM to PX Converter', 'Calculate responsive typography units based on customizable 16px root font size', 'design', 'type', 'REM Units'],
  ['fluid-clamp-calc', 'Fluid Typography clamp() Calculator', 'Generate CSS clamp(min, val, max) expressions for smoothly scaling screen fonts', 'design', 'maximize-2', 'Fluid Text'],
  ['text-shadow-gen', 'CSS Text-Shadow & Glow Builder', 'Design multi-layered text drop shadows and glowing neon effects with live CSS', 'design', 'type', 'Shadow'],
  ['triangle-gen', 'CSS Border Triangle Generator', 'Generate pure CSS directional arrows and tooltips using border width hacks', 'design', 'play', 'Shapes'],
  ['clip-path-gen', 'CSS Clip-Path Polygon Maker', 'Create custom geometric shapes, polygons, and stars using CSS clip-path', 'design', 'scissors', 'Clip-Path'],
  ['neumorphism-gen', 'CSS Neumorphism Soft UI Studio', 'Design soft extruded and inset shadow states for modern neumorphic interfaces', 'design', 'sun', 'Soft UI'],
  ['scrollbar-customizer', 'CSS Scrollbar Styler', 'Generate cross-browser ::-webkit-scrollbar and scrollbar-color CSS styles', 'design', 'sliders', 'Scrollbar'],
  ['color-shades-gen', 'Monochromatic Color Shades & Tints', 'Generate 10-step light-to-dark color scales (50 to 900) for UI design systems', 'design', 'palette', 'Shades'],
  ['svg-data-uri-gen', 'SVG to CSS Background Data URI', 'Encode raw SVG vector code into safe inline background-image data URI styles', 'design', 'image', 'Data URI'],
  ['css-filters-sandbox', 'CSS Filter Playground', 'Interactively adjust blur, brightness, contrast, grayscale, and invert filters', 'design', 'sliders', 'Filters'],
  ['css-animation-keyframes', 'CSS Keyframe Animation Studio', 'Build 0% to 100% keyframe transitions with pulse, bounce, and fade presets', 'design', 'play', 'Keyframes'],
  ['cubic-bezier-tester', 'Cubic-Bezier Easing Inspector', 'Visual cubic-bezier(x1, y1, x2, y2) timing curve generator for smooth transitions', 'design', 'activity', 'Easing'],
  ['css-specificity-calc', 'CSS Selector Specificity Calculator', 'Calculate (Inline, IDs, Classes, Elements) specificity scores for CSS rules', 'design', 'award', 'Specificity'],
  ['color-cmyk-converter', 'RGB & HEX to CMYK Print Converter', 'Convert screen colors to Cyan, Magenta, Yellow, and Key/Black print values', 'design', 'printer', 'CMYK'],
  ['tailwind-hex-lookup', 'Tailwind CSS Color Palette Lookup', 'Search official Tailwind CSS v3 & v4 hex colors by name (slate-800, indigo-600)', 'design', 'search', 'Tailwind'],
  ['css-var-scaffold', 'CSS Custom Property (:root) Scaffolder', 'Generate CSS variable design tokens for typography, spacing, and colors', 'design', 'file-text', 'Variables'],
  ['font-pair-tester', 'Heading & Body Font Pair Tester', 'Preview Google Fonts combinations side-by-side with adjustable scale ratios', 'design', 'type', 'Typography'],
  ['css-columns-builder', 'CSS Multi-Column Layout Maker', 'Configure column-count, column-gap, and column-rule for print-style text columns', 'design', 'columns', 'Columns'],
  ['css-backdrop-filter', 'Backdrop Filter Blur & Saturate', 'Generate iOS-style backdrop-filter blur backgrounds for navigation modals', 'design', 'sparkles', 'Backdrop'],
  ['golden-ratio-type', 'Golden Ratio Typography Scale Calculator', 'Calculate modular typographic scales based on the 1.618 golden ratio multiplier', 'design', 'trending-up', 'Scale'],
  ['css-cursor-directory', 'CSS Cursor Property Directory', 'Interactive preview of all CSS cursor states (pointer, grab, crosshair, not-allowed)', 'design', 'mouse-pointer', 'Cursor'],
  ['z-index-scale-manager', 'CSS z-index Elevation Scale Builder', 'Map organized z-index scales (dropdown 1000, modal 2000, toast 3000)', 'design', 'layers', 'z-index'],

  // 7. DEVOPS, CONTAINERS & LINUX
  ['cron-builder', 'Cron Expression Explainer', 'Translate 5-part cron syntax into human-readable sentences with presets', 'devops', 'clock', 'Crontab'],
  ['dockerfile-lint', 'Dockerfile Validator & Linter', 'Inspect Dockerfile instructions for caching efficiency and security practices', 'devops', 'container', 'Docker'],
  ['k8s-yaml', 'Kubernetes YAML Formatter', 'Format and validate Kubernetes Deployment, Service, and Ingress specs', 'devops', 'boxes', 'K8s'],
  ['chmod-calc', 'Linux Chmod Permissions Calculator', 'Calculate numeric (e.g. 755, 644) and symbolic (rwxr-xr-x) Linux permissions', 'devops', 'terminal-square', 'Chmod'],
  ['subnet-calc', 'IPv4 Subnet CIDR Calculator', 'Calculate network ranges, broadcast addresses, and usable host counts', 'devops', 'network', 'Networking'],
  ['ipv6-expand', 'IPv6 Address Expander & Compressor', 'Expand compressed zero sequences or shorten IPv6 addresses to standard RFC form', 'devops', 'cpu', 'IPv6'],
  ['nginx-format', 'Nginx Config Beautifier', 'Standardize tab indentations and block structures for Nginx server configs', 'devops', 'server', 'Nginx'],
  ['env-validator', '.env Environment File Sanitizer', 'Validate syntax, detect missing quotes, and strip comments from env files', 'devops', 'file-symlink', '.env'],
  ['git-commit', 'Git Commit Message Formatter', 'Format standardized Conventional Commit messages (feat, fix, chore, docs)', 'devops', 'git-commit', 'Commits'],
  ['ports-lookup', 'Common TCP/UDP Port Directory', 'Search well-known network ports (SSH 22, HTTP 80, HTTPS 443, Redis 6379)', 'devops', 'hash', 'Ports'],
  ['docker-to-compose', 'Docker Run to Docker Compose', 'Convert raw docker run CLI commands with flags (-p, -v, -e) into docker-compose.yml', 'devops', 'container', 'Compose'],
  ['compose-to-docker', 'Docker Compose to Docker Run CLI', 'Convert service definitions in docker-compose.yml into single docker run CLI commands', 'devops', 'terminal', 'Docker CLI'],
  ['k8s-configmap-env', 'Kubernetes ConfigMap from .env', 'Convert standard key=value .env files into Kubernetes ConfigMap manifest YAML', 'devops', 'boxes', 'ConfigMap'],
  ['k8s-secret-gen', 'Kubernetes Secret Manifest Generator', 'Encode plain text string values to Base64 and build Kubernetes Secret YAML manifests', 'devops', 'lock', 'Secrets'],
  ['helm-values-to-cli', 'Helm Values to CLI --set Flags', 'Flatten nested values.yaml YAML hierarchies into equivalent --set key.nested=val flags', 'devops', 'terminal', 'Helm'],
  ['nginx-rev-proxy', 'Nginx Reverse Proxy Config Maker', 'Generate production reverse proxy blocks with SSL, upstream, and proxy headers', 'devops', 'server', 'Nginx'],
  ['apache-htaccess-gen', 'Apache .htaccess 301 Redirect Builder', 'Generate clean RewriteRule 301 redirects and HTTPS redirect rules for Apache', 'devops', 'file-code', '.htaccess'],
  ['systemd-unit-builder', 'Systemd Service Unit Generator', 'Generate production Linux systemd service unit files with restart policies and user context', 'devops', 'cpu', 'Systemd'],
  ['ssh-fingerprint-calc', 'SSH Key Fingerprint Calculator', 'Compute SHA256 and MD5 public key fingerprints from pasted OpenSSH keys', 'devops', 'key', 'SSH'],
  ['apache-htpasswd-maker', 'Apache .htpasswd Generator', 'Generate Apache/Nginx basic authentication password hashes', 'devops', 'lock', 'htpasswd'],
  ['cidr-to-netmask', 'CIDR to Subnet & Wildcard Mask', 'Convert prefix notations (/24, /16) to dotted netmasks (255.255.255.0) and wildcard masks', 'devops', 'network', 'Netmask'],
  ['gh-actions-gen', 'GitHub Actions Workflow Builder', 'Generate CI/CD build, test, and deploy workflow YAML files for Node, Python, and Go', 'devops', 'play-circle', 'Workflows'],
  ['gitlab-ci-builder', 'GitLab CI Pipeline YAML Builder', 'Build multi-stage GitLab CI configuration files with cache and artifact rules', 'devops', 'file-text', 'GitLab'],
  ['gitignore-gen', 'Multi-Framework .gitignore Builder', 'Generate standard .gitignore rules for Node, Python, Java, macOS, and IDEs', 'devops', 'file-minus', '.gitignore'],
  ['shell-param-quoter', 'Shell Parameter Quoter & Sanitizer', 'Safely quote strings and sanitize variables to prevent bash injection vulnerabilities', 'devops', 'terminal', 'Bash'],
  ['bandwidth-time-calc', 'File Download Time Calculator', 'Calculate exact transfer durations across Mbps/Gbps connections for gigabyte files', 'devops', 'download', 'Transfer'],
  ['ping-overhead-calc', 'Ping Packet Overhead & MTU Calculator', 'Calculate packet fragmentation and IP/ICMP byte overhead for standard 1500 MTUs', 'devops', 'activity', 'MTU'],
  ['s3-policy-gen', 'AWS S3 Bucket Policy JSON Builder', 'Generate read-only, public-read, or restricted VPC bucket policies for Amazon S3', 'devops', 'shield', 'AWS S3'],
  ['iam-assume-role-gen', 'AWS IAM Trust Policy Generator', 'Generate AssumeRolePolicyDocument JSON for EC2, Lambda, and ECS task roles', 'devops', 'key', 'AWS IAM'],
  ['prometheus-alert-gen', 'Prometheus AlertRule YAML Builder', 'Format alert rules with for: durations, severity labels, and PromQL threshold expressions', 'devops', 'alert-triangle', 'Prometheus'],
  ['terraform-var-gen', 'Terraform Variable Block Scaffolder', 'Generate variable "name" { type = string, default = ... } blocks from JSON keys', 'devops', 'code', 'Terraform'],

  // 8. CONTENT, TEXT & MARKDOWN
  ['markdown-live', 'Markdown Live Previewer', 'Live Markdown to styled HTML renderer with word count and stats', 'text', 'file-text', 'Markdown'],
  ['word-counter', 'Word & Character Counter', 'Real-time word, character, sentence, paragraph, and reading time metrics', 'text', 'spell-check', 'Metrics'],
  ['case-convert', 'Text Case Converter', 'Switch text across Title Case, UPPERCASE, lowercase, camelCase, snake_case', 'text', 'type', 'Formatting'],
  ['dedupe-lines', 'Duplicate Line Remover', 'Remove duplicate rows, sort lines alphabetically, and strip empty whitespace', 'text', 'list-filter', 'Dedupe'],
  ['sort-lines', 'Alphabetical Line Sorter', 'Sort lists alphabetically (A-Z, Z-A), numerically, or by string length', 'text', 'arrow-down-narrow-wide', 'Sort'],
  ['whitespace-clean', 'Whitespace & Line Cleaner', 'Strip trailing whitespace, consecutive spaces, and blank carriage returns', 'text', 'eraser', 'Cleaner'],
  ['lorem-gen', 'Lorem Ipsum Text Builder', 'Generate placeholder paragraphs, sentences, or word counts for UI mockups', 'text', 'align-left', 'Mockup'],
  ['slug-to-title', 'Slug to Title String Generator', 'Convert kebab-case-url-slugs into readable capitalized article titles', 'text', 'text', 'Converter'],
  ['word-freq', 'Word Frequency Analyzer', 'Analyze text density, keyword counts, and lexical variety percentages', 'text', 'bar-chart-2', 'Analytics'],
  ['text-reverse', 'Text & String Reverser', 'Reverse full sentences, individual words, or character sequences', 'text', 'refresh-ccw', 'Transform'],
  ['html-to-markdown', 'HTML to Markdown Converter', 'Convert raw HTML web page elements and tags into clean Markdown formatting', 'text', 'file-text', 'HTML'],
  ['sql-in-wrapper', 'Delimited Text to SQL IN Wrapper', 'Wrap lines of text or IDs with single quotes and commas for SQL IN (\'a\', \'b\') queries', 'text', 'database', 'SQL IN'],
  ['extract-emails', 'Extract Emails from Unstructured Text', 'Scan unstructured text files to extract unique, deduplicated email addresses', 'text', 'mail', 'Extract'],
  ['extract-urls', 'Extract URLs from Raw Text', 'Identify, validate, and extract all web hyperlinks and URLs from bulk text blocks', 'text', 'link', 'Extract'],
  ['extract-ips', 'Extract IPv4 Addresses from Logs', 'Extract clean, deduplicated lists of IPv4 addresses from server error logs', 'text', 'network', 'Logs'],
  ['line-numberer', 'Text Line Numbering Tool', 'Prepend sequential line numbers to source text with customizable zero padding', 'text', 'list-ordered', 'Numbers'],
  ['prefix-suffix-tool', 'Batch Text Prefix & Suffix Appender', 'Prepend or append custom string tags to every line in a text document simultaneously', 'text', 'edit', 'Batch'],
  ['flesch-kincaid', 'Flesch-Kincaid Readability Calculator', 'Calculate reading ease score and grade level difficulty for technical documentation', 'text', 'book-open', 'Readability'],
  ['strip-html-tags', 'HTML Tag Stripper & Plain Text Extractor', 'Remove all HTML markup, scripts, and styles, leaving pure plain text content', 'text', 'trash-2', 'Cleaner'],
  ['zero-width-detector', 'Zero-Width Invisible Character Detector', 'Detect and remove hidden Unicode zero-width spaces that break code parsing', 'text', 'eye-off', 'Sanitizer'],
  ['diff-inline-checker', 'Inline Character-by-Character Diff', 'Highlight micro text changes, typo fixes, and punctuation diffs inline', 'text', 'git-commit', 'Diff'],
  ['palindrome-checker', 'Palindrome Phrase & Sentence Verifier', 'Check if alphanumeric character sequences read identically forwards and backwards', 'text', 'refresh-cw', 'Palindrome'],
  ['string-truncator', 'Word-Boundary Smart String Truncator', 'Truncate paragraphs to max characters without chopping words in half', 'text', 'scissors', 'Truncate'],
  ['comma-to-newline', 'Comma to Newline & List Transposer', 'Convert comma-delimited strings into vertical lists or newline lists to commas', 'text', 'list', 'Delimit'],
  ['extract-hex-colors', 'Extract Hex Color Codes from CSS', 'Scan CSS and text blocks to extract unique 3, 6, and 8-digit #hex color codes', 'text', 'pipette', 'Extract'],
  ['nato-phonetic-gen', 'NATO Phonetic Alphabet Speller', 'Convert text (Alpha, Bravo, Charlie) for clear spelling over voice phone calls', 'text', 'mic', 'Phonetic'],
  ['morse-code-codec', 'Morse Code Encoder & Decoder', 'Translate text into dots and dashes (. ---) and decode Morse back into letters', 'text', 'radio', 'Morse'],
  ['bbcode-to-html', 'BBCode to HTML Markup Converter', 'Convert forum BBCode tags ([b], [url], [quote]) into clean semantic HTML5', 'text', 'code', 'BBCode'],
  ['markdown-checklist-calc', 'Markdown Checklist Progress Tracker', 'Calculate percentage completion from - [x] done and - [ ] todo markdown checkboxes', 'text', 'check-square', 'Checklist'],
  ['binary-to-text', 'Binary (01) to ASCII Text Converter', 'Convert 8-bit space-separated binary byte streams into readable English text', 'text', 'binary', 'Binary'],
  ['text-to-binary', 'Text to 8-Bit Binary Representation', 'Encode ASCII and UTF-8 strings into binary byte representations', 'text', 'binary', 'Binary'],
  ['leetspeak-generator', 'LeetSpeak (1337) Text Generator', 'Transform standard text into hacker leetspeak with customizable letter substitutions', 'text', 'terminal', '1337'],

  // 9. MATH, TIME & FINANCIAL
  ['base-converter', 'Number Base Converter', 'Simultaneous live conversion across Decimal, Hexadecimal, Binary, and Octal', 'math', 'binary', 'Base 2-16'],
  ['unit-convert', 'Universal Unit Converter', 'Convert length, mass, temperature, data storage, and speed instantly', 'math', 'scale', '6 Categories'],
  ['percent-calc', 'Percentage Calculator', 'Calculate percentage increase, decrease, fraction ratios, and discounts', 'math', 'percent', 'Math'],
  ['unix-epoch', 'UNIX Timestamp to Date Converter', 'Convert millisecond/second epoch timestamps to human-readable ISO and local time', 'math', 'calendar-clock', 'Time'],
  ['date-epoch', 'Human Date to UNIX Epoch', 'Select any calendar date and time to compute the exact UTC UNIX timestamp', 'math', 'calendar', 'Timestamp'],
  ['byte-calc', 'Byte & Bit Storage Calculator', 'Convert between B, KB, MB, GB, TB, and network bitrate units (Kbps, Mbps)', 'math', 'hard-drive', 'Storage'],
  ['gcd-lcm', 'GCD & LCM Calculator', 'Calculate Greatest Common Divisor and Least Common Multiple of numbers', 'math', 'calculator', 'Arithmetic'],
  ['roman-num', 'Roman Numeral Converter', 'Convert standard integers into Roman numerals and parse Roman numerals to digits', 'math', 'columns', 'Numerals'],
  ['speed-conv', 'Speed & Velocity Converter', 'Convert between km/h, mph, m/s, knots, and Mach numbers', 'math', 'gauge', 'Velocity'],
  ['temp-conv', 'Temperature Scale Converter', 'Simultaneously convert across Celsius, Fahrenheit, Kelvin, and Rankine scales', 'math', 'thermometer', 'Temp'],
  ['date-diff-calc', 'Days Between Dates Calculator', 'Calculate exact calendar days, weeks, months, and hours between two dates', 'math', 'calendar', 'Date Math'],
  ['work-days-calc', 'Working Days & Business Hours Calculator', 'Calculate business days between dates, automatically excluding weekends', 'math', 'clock', 'Work Days'],
  ['date-add-sub', 'Date Addition & Subtraction Calculator', 'Add or subtract days, weeks, months, or years to project future milestone deadlines', 'math', 'calendar-plus', 'Schedule'],
  ['timezone-overlap', 'Timezone Meeting Planner', 'Visualize overlapping working business hours across IST, UTC, EST, and PST', 'math', 'globe', 'Timezones'],
  ['loan-emi-calc', 'Loan EMI & Amortization Calculator', 'Calculate monthly loan EMI and view interest vs principal amortizations', 'math', 'calculator', 'Finance'],
  ['sip-calc', 'SIP Compound Interest Calculator', 'Calculate future returns on monthly systematic mutual fund investment plans', 'math', 'trending-up', 'Investment'],
  ['compound-interest', 'Compound Interest Calculator', 'Calculate compound growth over time with annual, monthly, or daily compounding', 'math', 'pie-chart', 'Compound'],
  ['reverse-tax-calc', 'Reverse Tax / GST Deduction Calculator', 'Calculate pre-tax base prices and tax components from gross inclusive totals', 'math', 'percent', 'Taxes'],
  ['profit-margin-calc', 'Profit Margin & Markup Calculator', 'Calculate gross profit, percentage markup, and sales revenue margins', 'math', 'trending-up', 'Margins'],
  ['cagr-calc', 'CAGR (Annual Growth Rate) Calculator', 'Calculate Compound Annual Growth Rate for business revenue and portfolio investments', 'math', 'bar-chart', 'CAGR'],
  ['fuel-trip-calc', 'Trip Fuel & Cost Estimator', 'Estimate total fuel volume and currency expenses based on distance and mileage', 'math', 'navigation', 'Travel'],
  ['scientific-notation', 'Scientific Notation Converter', 'Convert numbers to scientific exponential notation (1.23e+8) and vice versa', 'math', 'hash', 'Scientific'],
  ['rule-of-72-calc', 'Rule of 72 Doubling Time Calculator', 'Estimate how many years it takes for an investment to double at a given interest rate', 'math', 'clock', 'Rule of 72'],
  ['simple-interest-calc', 'Simple Interest & Payoff Calculator', 'Calculate basic non-compounding interest ($I = P \\times r \\times t$) on loans', 'math', 'dollar-sign', 'Interest'],
  ['tip-bill-splitter', 'Restaurant Tip & Group Bill Splitter', 'Calculate tip percentages and split total restaurant checks evenly among party guests', 'math', 'users', 'Bill Split'],
  ['fraction-reducer', 'Fraction Simplifier & Reducer', 'Simplify complex fractions to lowest terms and convert to decimal equivalents', 'math', 'divide', 'Fractions'],
  ['prime-factor-calc', 'Prime Number Factorization Calculator', 'Test if an integer is prime and view its complete prime factor breakdown tree', 'math', 'hash', 'Primes'],
  ['quadratic-solver', 'Quadratic Equation ($ax^2+bx+c$) Solver', 'Calculate real and complex roots for standard algebraic quadratic formulas', 'math', 'help-circle', 'Algebra'],
  ['statistics-mean-median', 'Mean, Median, Mode & Range Calculator', 'Calculate central tendency statistics from comma-delimited numeric datasets', 'math', 'bar-chart-2', 'Statistics'],
  ['std-dev-calc', 'Standard Deviation & Variance Calculator', 'Calculate population and sample variance ($s^2$) and standard deviation ($\\sigma$)', 'math', 'activity', 'Variance'],
  ['random-num-range', 'Cryptographic Random Integer Picker', 'Generate uniform random numbers within custom min/max integer boundaries', 'math', 'shuffle', 'Random'],

  // 10. FILE, MEDIA & CANVAS UTILITIES
  ['img-compress', 'Image Compressor & WebP', 'Reduce PNG/JPG file sizes and convert to next-gen WebP directly in Canvas', 'media', 'image', 'WebP Canvas'],
  ['b64-canvas', 'Base64 Image Inspector', 'Paste Base64 data URLs to preview dimensions, aspect ratio, and download image', 'media', 'file-image', 'Inspector'],
  ['b64-file', 'Base64 to File Downloader', 'Convert Base64 data strings back into downloadable binary files', 'media', 'file-down', 'Decoder'],
  ['svg-optimizer', 'SVG Code Optimizer & Cleaner', 'Strip XML metadata, empty groups, and comments to optimize SVG vector code', 'media', 'feather', 'SVG'],
  ['ico-generator', 'Favicon Dimension Sizer', 'Resize and export raster graphics into standard 16x16, 32x32, and 512x512 assets', 'media', 'app-window', 'Favicon'],
  ['audio-tone', 'DTMF Audio Tone Generator', 'Synthesize custom frequency sine-wave audio tones using Web Audio API', 'media', 'volume-2', 'Audio'],
  ['color-extractor', 'Image Dominant Color Extractor', 'Upload images to extract primary hex color swatches and color palettes', 'media', 'droplet', 'Swatches'],
  ['qr-scanner-mock', 'Camera QR Code Reader Simulator', 'Simulate decoding QR code image payloads and data URI payloads locally', 'media', 'scan', 'Scanner'],
  ['markdown-pdf', 'Markdown Printable Export', 'Render Markdown notes into clean, printable document layouts with pagination', 'media', 'printer', 'Print'],
  ['code-snippet-card', 'Code Snippet Card Studio', 'Design stylized image cards for code snippets with gradient backgrounds', 'media', 'camera', 'Cards'],
  ['pdf-page-extract', 'Client-Side PDF Page Extractor', 'Extract and save individual page ranges from PDF files locally using pdf-lib', 'media', 'file-text', 'pdf-lib'],
  ['image-resizer-canvas', 'Canvas Image Resizer & Scaler', 'Scale image dimensions by percentage or target width/height without uploading files', 'media', 'maximize', 'Canvas'],
  ['svg-to-png', 'SVG Vector to High-Res PNG Exporter', 'Render scalable SVG vector markup onto high-resolution raster PNG images', 'media', 'image', 'Rasterizer'],
  ['canvas-drawing', 'HTML5 Canvas Sketchpad', 'In-browser drawing board with exportable PNG drawing capabilities', 'media', 'edit-3', 'Canvas'],
  ['color-tint-canvas', 'Image Monochromatic Tint Filter', 'Apply custom color overlays and tints to uploaded images in browser memory', 'media', 'palette', 'Image Filter'],
  ['file-checksum-hasher', 'Drag-and-Drop File Hash Checksum', 'Compute SHA-256 and MD5 checksum digests of any local file without uploading', 'media', 'check-square', 'Checksum'],
  ['screen-dpi-checker', 'Screen DPI & Device Pixel Ratio Inspector', 'Inspect screen color depth, viewport dimensions, and window.devicePixelRatio', 'media', 'monitor', 'Screen'],
  ['keycode-inspector', 'Keyboard Event & KeyCode Inspector', 'Test key presses to view event.key, event.code, and event.which properties live', 'media', 'keyboard', 'Events'],
  ['exif-metadata-viewer', 'EXIF Metadata & Camera Tag Inspector', 'Read camera model, focal length, ISO, and GPS location tags from uploaded photos', 'media', 'camera', 'EXIF'],
  ['exif-metadata-stripper', '1-Click Privacy EXIF Metadata Stripper', 'Strip GPS geolocation and camera serial tags from photos before online sharing', 'media', 'shield', 'Privacy'],
  ['image-to-base64', 'Image File to Base64 Data URI', 'Upload PNG/JPG images and copy clean data:image/png;base64,... code strings', 'media', 'file-image', 'Base64'],
  ['barcode-generator', 'Barcode CODE128 & EAN-13 Generator', 'Generate printable vector barcodes for inventory tracking and retail products', 'media', 'align-justify', 'Barcode'],
  ['dead-pixel-tester', 'Monitor Dead Pixel Color Test Bed', 'Cycle full-screen solid red, green, blue, black, and white to reveal stuck pixels', 'media', 'monitor', 'Display'],
  ['webcam-snapshot-tester', 'Webcam Hardware Frame Grabber', 'Capture camera snapshots and verify local video permissions without external servers', 'media', 'video', 'Webcam'],
  ['mic-decibel-meter', 'Microphone Decibel (dB) Audio Meter', 'Monitor ambient room noise and microphone input volume levels in real time', 'media', 'mic', 'Audio'],
  ['speech-synthesis-test', 'Web Speech Synthesis Voice Simulator', 'Test browser text-to-speech voices with adjustable pitch, rate, and volume', 'media', 'volume-2', 'Voice'],
  ['speech-recognition-test', 'Web Speech-to-Text Dictation Sandbox', 'Live speech transcription testing microphone speech recognition accuracy', 'media', 'mic-off', 'Dictation'],
  ['gamepad-tester', 'Gamepad & Controller Event Tester', 'Test analog sticks, triggers, and buttons for connected USB and Bluetooth controllers', 'media', 'play', 'Gamepad'],
  ['mouse-click-accuracy', 'Mouse Click & Double-Click Latency Tester', 'Measure click response latency (ms) and test mouse button double-click triggers', 'media', 'mouse-pointer', 'Mouse'],
  ['vibration-api-tester', 'Mobile Vibration API Pattern Tester', 'Trigger custom vibration pulse patterns ([200, 100, 200]) on supported smartphones', 'media', 'smartphone', 'Haptics'],
  ['battery-status-inspector', 'Battery Level & Charging Status Inspector', 'Inspect battery charge percentage and discharging time via navigator.getBattery()', 'media', 'battery-charging', 'Battery']
];
